-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.certifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  issuing_organization text NOT NULL,
  issue_date date NOT NULL,
  expiry_date date,
  credential_id text,
  credential_url text,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT certifications_pkey PRIMARY KEY (id),
  CONSTRAINT certifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.education (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  institution text NOT NULL,
  degree text NOT NULL,
  field_of_study text NOT NULL,
  start_date date,
  end_date date,
  graduation_date date,
  gpa numeric,
  max_gpa numeric DEFAULT 4.0,
  honors ARRAY,
  relevant_coursework ARRAY,
  activities ARRAY,
  display_order integer DEFAULT 0,
  is_current boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT education_pkey PRIMARY KEY (id),
  CONSTRAINT education_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.generated_materials (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  material_type text NOT NULL CHECK (material_type = ANY (ARRAY['resume'::text, 'cover_letter'::text, 'linkedin_message'::text, 'email_template'::text])),
  job_id text,
  company_name text,
  job_title text,
  content text NOT NULL,
  version text,
  ai_model_used text,
  generation_cost numeric,
  quality_score integer,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '30 days'::interval),
  CONSTRAINT generated_materials_pkey PRIMARY KEY (id),
  CONSTRAINT generated_materials_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.job_preferences (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  desired_roles ARRAY DEFAULT '{}'::text[],
  experience_level text CHECK (experience_level = ANY (ARRAY['Intern'::text, 'Entry Level'::text, 'Mid Level'::text, 'Senior'::text, 'Lead'::text, 'Principal'::text])),
  min_salary integer,
  max_salary integer,
  salary_currency text DEFAULT 'USD'::text,
  preferred_locations ARRAY DEFAULT '{}'::text[],
  remote_preference text CHECK (remote_preference = ANY (ARRAY['Remote Only'::text, 'Hybrid'::text, 'On-site'::text, 'No Preference'::text])),
  willing_to_relocate boolean DEFAULT false,
  job_types ARRAY DEFAULT '{}'::text[],
  company_sizes ARRAY DEFAULT '{}'::text[],
  industries ARRAY DEFAULT '{}'::text[],
  work_authorization text,
  requires_sponsorship boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT job_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  full_name text NOT NULL,
  email text NOT NULL,
  phone text,
  location text,
  github_url text,
  linkedin_url text,
  portfolio_url text,
  profile_complete boolean DEFAULT false,
  onboarding_step integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text NOT NULL,
  role text,
  project_url text,
  github_url text,
  demo_url text,
  technologies ARRAY,
  key_features ARRAY,
  start_date date,
  end_date date,
  is_ongoing boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.skills (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['Programming Languages'::text, 'Frameworks'::text, 'Databases'::text, 'Tools'::text, 'Cloud'::text, 'Soft Skills'::text, 'Other'::text])),
  name text NOT NULL,
  proficiency text CHECK (proficiency = ANY (ARRAY['Beginner'::text, 'Intermediate'::text, 'Advanced'::text, 'Expert'::text])),
  years_of_experience integer,
  is_primary boolean DEFAULT false,
  endorsements integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT skills_pkey PRIMARY KEY (id),
  CONSTRAINT skills_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.work_experience (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  company text NOT NULL,
  job_title text NOT NULL,
  employment_type text CHECK (employment_type = ANY (ARRAY['Full-time'::text, 'Part-time'::text, 'Contract'::text, 'Internship'::text, 'Freelance'::text])),
  location text,
  start_date date NOT NULL,
  end_date date,
  is_current boolean DEFAULT false,
  description text,
  achievements ARRAY,
  technologies_used ARRAY,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT work_experience_pkey PRIMARY KEY (id),
  CONSTRAINT work_experience_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);